"""Add StyleSnippet and Chapter.warnings

Revision ID: 9f5bd7193824
Revises: b5892a224d1b
Create Date: 2026-07-12 07:00:24.550017

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f5bd7193824'
down_revision: Union[str, Sequence[str], None] = 'b5892a224d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warnings', sa.Text(), nullable=True))

    op.create_table('style_snippets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_snippets')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('warnings')

    # ### end Alembic commands ###
