"""add metadata_json and summary columns

Revision ID: b052df1ff8eb
Revises: 9f5bd7193824
Create Date: 2026-07-12 08:53:04.307554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b052df1ff8eb'
down_revision: Union[str, Sequence[str], None] = '9f5bd7193824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    with op.batch_alter_table('glossary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sa.Text(), nullable=True))

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    with op.batch_alter_table('glossary', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
